Add RandomFloat4D node
arkology/ShaderV pull request #22
Opened 2024-04-17 13:27 UTC by AlexeyBond

This adds a random noise function I previously added to https://github.com/Maujoe/Godot-Visual-Shader-Node-Library (which wasn't ported to Godot 4).

A random function with more than 2 inputs makes it possible to generate a 2D noise changing over time - that's what I tried to do recently using this addon but couldn't find an appropriate node.

2024-04-18 08:47 UTC, arkology commented
Thanks a lot for your contribution! 
I'll try to review (I'm sure everything is fine, but still) and merge at nearest weekends. 

Also it would be great if you will create another PR to backport changes to 3.x branch (https://github.com/arkology/ShaderV/tree/godot-3.x) after merging this PR. Or I could backport if by myself, it's not a problem.

2024-04-18 12:45 UTC, AlexeyBond commented on addons/shaderV/tools/random/randomFloat4D.gd
> +		offset = 'vec4(0)'
🤦 Godot doesn't handle default values on Vector4 inputs

https://github.com/godotengine/godot/pull/90850

2024-04-21 15:20 UTC, arkology requested changes
ATM I get following errors when disconnecting `input` or `offset` inputs of RandomFloat4D node in basic_examples scene:
```
  res://addons/shaderV/examples/basic_examples.tscn::VisualShader_y00xk:19 - Invalid arguments to operator '+': 'vec3, vec4'.
  Shader compilation failed.
--res://addons/shaderV/examples/basic_examples.tscn::VisualShader_y00xk--
    1 | shader_type canvas_item;
    2 | render_mode blend_mix;
    3 | 
    4 | 
    5 | 
    6 | 
    7 | #include "res://addons/shaderV/tools/random/randomFloat4D.gdshaderinc"
    8 | 
    9 | 
   10 | void fragment() {
   11 | 
   12 |  float n_out8p0 = TIME;
   13 | 
   14 | 
   15 |  float n_out9p0;
   16 | 
   17 |  vec3 n_in9p0 = vec3(0.00000, 0.00000, 0.00000);
   18 |  float n_in9p1 = 1.00000;
E  19->  {
   20 |  n_out9p0 = _randFloat4D(n_in9p0 * n_in9p1 + vec4(n_out8p0));
   21 |  }
   22 | 
   23 | 
   24 | 
   25 |  COLOR.rgb = vec3(n_out9p0);
   26 | 
   27 | 
   28 | }
   29 | 
--res://addons/shaderV/tools/random/randomFloat4D.gdshaderinc--
    1 | highp float _randFloat4D(vec4 input) {
    2 |  float f = dot(fract(input) + fract(input * 2.32184321231),vec4(129.898,782.33,944.32214932,122.2834234542));
    3 |  return fract(sin(f) * 437588.5453);
    4 | }
    5 | 
```

2024-04-21 16:04 UTC, AlexeyBond commented on addons/shaderV/examples/basic_examples.tscn
> -default_input_values = [0, Vector3(0, 0, 0), 1, 1.0, 2, Vector3(0, 0, 0)]
There were invalid default values from previous iteration stored in the scene. It should be fine now.

2024-04-28 10:10 UTC, arkology approved these changes

2024-04-28 10:22 UTC, merged

2024-04-28 10:22 UTC, arkology commented
Thanks!